version: '3.8'

services:
  api:
    build:
      context: ./nfactorial-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always
    volumes:
      - ./nfactorial-backend:/app
      - /app/node_modules
    depends_on:
      - redis

  frontend:
    build:
      context: ./nfactorial-frontend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./nfactorial-frontend/.env


  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data: